spring.application.name=question-mark

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/questionario
spring.datasource.username=postgres
spring.datasource.password=clara123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Upload de imagens das perguntas
app.upload.max-size-bytes=2097152
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
